#!/bin/sh
bin_dir="$HOME/.local/bin"
prefix="===>"

msg() {
	for msg in "$@"; do
		printf '%s %s\n' $prefix "$msg"
	done
}

install() {
	for f in bin/**; do
		f="$(realpath "$f")"
		msg "Installing $f"
		ln -sf "$f" "$bin_dir"
	done
	msg "Done installing."
}



printf "Recursively link scripts in ./bin to %s? [y/N]: " "$bin_dir"
read -r continue

case "$continue" in
	[Yy]* ) install;;
	* ) msg "Not installing."
esac
