#!/bin/sh
bin_dir="$HOME/.local/bin"
pre="===>"

msg() {
	format="$pre $1\n"
	shift
	printf "$format" $@
}

install() {
	for f in bin/**; do
		f="$(realpath $f)"
		msg "Installing %s" "$f"
		ln -sf "$f" "$bin_dir"
	done
	msg "Done installing."
}



printf "Recursively link scripts in ./bin to %s? [y/N]: " "$bin_dir"
read continue

case "$continue" in
	[Yy]* ) install;;
	* ) msg "Not installing."
esac
